# Generated by Django 2.0.1 on 2018-01-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantname', models.CharField(max_length=50)),
                ('foodtype', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(max_length=50)),
                ('website', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'restaurantInfo',
            },
        ),
        migrations.DeleteModel(
            name='foodmapsite',
        ),
    ]
