# Generated by Django 2.0.1 on 2018-01-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homemap', '0004_auto_20180122_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantinfo',
            name='website',
        ),
    ]
